### ISSUE TITLE
[Server] [1.10.2] Server Crash on load

### ISSUE THREAD

**Issue by aking4125** [TeamDman/Animus#20]
Client works fine. Server crashes relating to Audio.

[crash-2016-11-20_16.17.22-server.txt](https://github.com/TeamDman/Animus/files/602342/crash-2016-11-20_16.17.22-server.txt)

**Comment by JohnKrell007** [comment]
Second that.

**Comment by Saereth** [comment]
Thanks for the report guys, I'm on it Teamy, should have a fix soonish.

**Comment by Saereth** [comment]
This is fixed in the next build, teamy should have it on curseforge in a bit.

**Comment by TeamDman** [comment]
Build should be up
