### ISSUE TITLE
Sigil of Consumption crashes when used on Railcraft Abyssal Stone

### ISSUE THREAD

**Issue by rdp1408** [TeamDman/Animus#44]
Client crashes to desktop when attempting to use sigil of consumption on Railcraft Abyssal Stone.

crashlog:
[crash-2016-12-20_22.02.13-client.txt](https://github.com/TeamDman/Animus/files/665372/crash-2016-12-20_22.02.13-client.txt)

**Comment by TeamDman** [comment]
if (worldIn.getTileEntity(pos) != null || worldIn.getBlockState(pos).getBlock().getBlockHardness(null,null,null)==-1.0F)

railcraft returns null on getBlockState for abyssal stone .-.

Will add fix later

**Comment by TeamDman** [comment]
Has been fixed for a while, whoops
