### ISSUE TITLE
MineTweaker NPE with basic animus recipe change

### ISSUE THREAD

**Issue by OrdinatorStouff** [TeamDman/Animus#46]
I have a minetweaker script with only these contents in it:
```
//====Diamond Khopesh====
recipes.remove(<animus:itemkamadiamond>);
recipes.addShaped(<animus:itemkamadiamond>,
[[null, <ore:gemDiamond>, null],
 [<ore:gemDiamond>, <bloodmagic:ItemSlate:2>, <ore:gemDiamond>]
 [null, null, <botania:incenseStick>]]);
```
and when I try to load a single player world, the "internal server" will crash (but not generate a log) and hang the client until forcibly closed by task manager. The relevant part of the latest.log should be all of this: https://pastebin.com/eiYs68RH and it only seems to point to MineTweaker classes but since this is only happening for Animus items I figured I'd report here first. This is an "expert" pack so there are literally thousands of lines of minetweaker scripts across over 60 script files and none of them cause this issue.

EDIT:
Animus 20170327
CraftTweaker 1.10.2-1.3.7
ModTweaker 2.0.11
MTLib 1.0.2

**Comment by Saereth** [comment]
Crash was related to ClassCache mod, not applicable to us but good to look out for in the future

**Comment by Saereth** [comment]
I cannot reproduce this despite multiple attempts, http://imgur.com/a/dr49M
any idea what may be causing this @jaredlll08 ?

**Comment by OrdinatorStouff** [comment]
Most likely an issue with another mod or another mt script. This *should* be reproducible using the (currently alpha) 1.0.31 version of AllTheMods: Expert where I'm experiencing it. Sixty other mt scripts are there, and adding this one recipe change for animus causes this "crash" (quotes because no crash-log is generated).

This is the full contents of the minetweaker script that it's "hanging" on:
https://pastebin.com/ZTScwKCx

This is the minetweaker.log, it stops after AE2 zs, the next alphabetical zs that would be next is animus:
https://pastebin.com/FZFAxRL3

This is the full fml-server-latest.log. Relevant NPE around line# 24978:
https://paste.ubuntu.com/24269041/

**Comment by Saereth** [comment]
Nothing to see Here... 👍
