### ISSUE TITLE
Item request from Mr Black - Sanguine Observer

### ISSUE THREAD

**Issue by Saereth** [TeamDman/Animus#62]
Add a block to generate a redstone comparator signal based on the player's LP network. Would link to the uuid of the person that places the block (save in nbt) and then generate a comperator signal based on the full % of the players lp network.

**Comment by TeamDman** [comment]
https://github.com/WayofTime/BloodMagic/blob/1.12/src/main/java/WayofTime/bloodmagic/block/BlockAltar.java#L54

Bloodstone brick below the altar with an orb in it already has this functionality
