### ISSUE TITLE
Add single healing fragment effect, fix slot locking

### ISSUE THREAD

**Issue by TeamDman** [TeamDman/Animus#64]
1/2 heart every minute with 1 shard in inventory
investigate inventory slot locking

**Comment by Saereth** [comment]
Escapee fixed with a PR here
https://github.com/TeamDman/Animus/pull/65

**Comment by TeamDman** [comment]
Last time I was messing around with it, there were cases where the fragment slots weren't locked, might need more investigation. The merged PR fixes the part about unlocking the slots when they no longer have fragments, which was a separate issue; might still be more to do here but will be closed for now.
Thanks for the PR!
