### ISSUE TITLE
Sigil of Natures Leech and IC2

### ISSUE THREAD

**Issue by kad73092** [TeamDman/Animus#74]
When you have an activated Sigil of Natures Leech in your inventory, Industrial Craft 2 Machines within its area of effect disappear/explode. They will also disappear from your inventory as though they were consumed.

**Comment by Saereth** [comment]
wat... this is a joke right? it only looks for blocks that extend IPlantable, which definitely would not include ic2 machines. Can you give us some specifics, forge version/ic2 version etc so we can try and reproduce

**Comment by kad73092** [comment]
As dumb as it sounds, no, it is not a joke. I tested it by turning on and off the sigil, and it only happened while active. Playing in the most up to date version of Enigmatica 2 Expert.
Forge Version - 14.23.5.2781
Industrialcraft - 2-2.8.120

**Comment by TeamDman** [comment]
![image](https://user-images.githubusercontent.com/9356891/58219462-04b18100-7cd9-11e9-937b-38ee126558e5.png)
That's uhh... yup. Looking into it.

**Comment by TeamDman** [comment]
So this is a thing
![image](https://user-images.githubusercontent.com/9356891/58220474-0715da00-7cdd-11e9-9792-90b928cf1116.png)

**Comment by alexlarex** [comment]
The fix didn't fix the consumption of IC2 machines and cables from the world, as it only checks the blacklist for the items in the inventory, it seems.
