### ISSUE TITLE
Ritual of Eldritch Will help&bug

### ISSUE THREAD

**Issue by Sandman366** [TeamDman/Animus#77]
Trying to understand how to use Ritual of Eldritch Will (because the CurseForge page doesn't say much and I can't find any other documentation). I _think_ I've figured it out: just setup the ritual and it exports into Will Aura, right? Or does it need something else? (And it's just so super insanely slow that the only time I've seen it work so far is breaking MRS and activating again? What unit is "speed" in, anyway? Minutes?)

While trying to figure it out, I did find another issue: the runes. It only places 16, but says it needs 17...looks like it's short a dusk rune. (Which it seems to say the ritual works just fine without, which also confused me 'til I tried glancing at source.)

Don't know how to suggest edits directly so I'll just put it here:
src/main/java/com/teamdman/animus/rituals/RitualEldritchWill.java
Lines 124 and 125 are duplicates, one of them needs to be BlockPos(-3, 1, -3).

(Also on yet another thing at looking at the source for the ritual....maybe I just don't know how to read this, but to me it looks like it checks if Thaumcraft is loaded, and if it is, then "refreshTime" is 10,000, and if it's not, then use config time to refresh ritual. Similar story for "refreshCost", except that goes to 0 instead of config.)

**Comment by Saereth** [comment]
I'll do some testing and fix this up today. oddly enough its working for me in all the mods expert 3 shedding tiers pack atm. The duplicate rune is definitely a mistake but weird that it runs without it. The refresh time is just a reversed boolean.

The refresh time is in ticks so (20/s) if the server isnt lagging. Expect a new jar with the fixes on curseforge this evening

**Comment by Sandman366** [comment]
Does actually work without repeatedly restarting the ritual, just didn't see it at the time, so it's just a duplicate rune placement check and really slow. (And also didn't at first realize it went into Will Aura, for some reason I expected Will items.)

**Comment by Saereth** [comment]
resolved in https://github.com/TeamDman/Animus/commit/97798ba826eceef282a3ad0a511a9b53d05065e5

Also updated the curseforge page to better explain that it's creating demon will aura and not the items.
