### ISSUE TITLE
Guide missing

### ISSUE THREAD

**Issue by theceige** [TeamDman/Animus#79]
I have the latest Guide-API installed along with the newest version of Blood Magic and Animus. I can not find the guide anywhere. I am using JEI and searching by @Guide-API or @Animus does not return any items that look like a guide for me. Dug around in the jar file a bit and couldn't find anything related although I can't say I would know where to look exactly or even what I'm looking for. I have never used the mod before now so I don't know what the guide is supposed to look like. However I was able to find the guide-api files in blood magic for it's own guide. So I suspect the files are missing. I tried your last upload and the one before that. No luck unfortunately. I've tried to figure it out on my own but I would appreciate some feedback to help me out here. I don't know how to build any of these rituals.

**Comment by TeamDman** [comment]
The guidebook may not have been ported from 1.7.10, most of the information should be available on the curse forge page.

For the rituals, Blood Magic has an item called "Ritual Diviner" that will automatically build the ritual for you when you right click a master ritual stone with blank ritual stones in your inventory. Hopefully we will be able to prioritize better documentation in a future release

**Comment by theceige** [comment]
I appreciate your timely response. I will use the ritual diviner as you suggest later today.  As a side note, what is required for writing this documentation? If I do not need any intimate knowledge of coding, perhaps once I am more familiar with the mod I can help. Is it just the process of creating something like the Sanguine Scientem in-game and perhaps a wiki of some sort online?

**Comment by TeamDman** [comment]
We will likely be implementing a Patchouli solution for future guidebooks, it will mainly involve coding but we appreciate the offer!
