### ISSUE TITLE
Leech blacklist works only for inventory items

### ISSUE THREAD

**Issue by alexlarex** [TeamDman/Animus#80]
The fix for #74 didn't actually fix it completely, the blacklist doesn't check for blocks in world, only for those in the inventory. So IC2 machines and cables are still eaten by the sigil, when near them. Also it seems that IC2 cables should be in this blacklist by default too.

**Comment by alexlarex** [comment]
Can be fixed by adding the same config check from ItemSigilLeech.getFood to ItemSigilLeech.eatGrowables

**Comment by alexlarex** [comment]
Also, even though I didn't check its behavior in game, the Ritual of the Natures Leech doesn't have this check too, so it quite probably will eat IC2 machines and cables as well.

**Comment by TeamDman** [comment]
Thanks for noticing this, will fix it ~Monday when I'm home from break :)

**Comment by TeamDman** [comment]
https://www.curseforge.com/minecraft/mc-mods/animus/files/2888473
Fix should be available soon!
Make sure to add `minecraft:grass` to your leech blacklist, since it now detects IGrowables too.
