### ISSUE TITLE
Ritual of culling not killing the Ender Dragon

### ISSUE THREAD

**Issue by Hatmic98** [TeamDman/Animus#83]
Hi there. I'm wondering why the Ender Dragon that i have spawned is not being killed by a ritual of culling. I have made sure that the destructive will in its chunk is capped. i have also verified that the range of the ritual is correct and working. The Wither dies as expected but the Ender Dragon does not.

**Comment by Saereth** [comment]
eh ender dragon is a bit of a special case as its actually like multiple entities might be worth adding in the future but was outside of the scope of the original idea

**Comment by Hatmic98** [comment]
Ahh alright, not a problem. Thank you for your time.
